dist: xenial

services:
  - elasticsearch

language: python

matrix:
  fast_finish: true
  include:
  - env: TOX_ENV=py27-django111
    python: 2.7
  - env: TOX_ENV=py35-django20
    python: 3.5
  - env: TOX_ENV=py36-django111
    python: 3.6
  - env: TOX_ENV=py36-django20
    python: 3.6
  - env: TOX_ENV=py36-django21
    python: 3.6
  - env: TOX_ENV=py36-django22
    python: 3.6
  - env: TOX_ENV=py37-django20
    python: 3.7
  - env: TOX_ENV=py37-django21
    python: 3.7
  - env: TOX_ENV=py37-django22
    python: 3.7

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.16.deb && sudo dpkg -i --force-confnew elasticsearch-5.6.16.deb && sudo service elasticsearch restart

install: pip install -r examples/requirements/test.txt

before_script:
  - sleep 10

script: travis_retry tox -e $TOX_ENV
